### ISSUE TITLE
step to deploy Wukong on AWS Lambda

### ISSUE THREAD

**Issue by photoszzt** [mason-leap-lab/Wukong#3]
It would be great if you could provide steps to deploy the Wukong on AWS Lambda and reproduce the result in the paper.

**Comment by photoszzt** [comment]
Which version of dask and dask distributed this project compares to? In the changelog of the static scheduler, I see 1.28.1 at the top. Is that the version you are comparing to?

**Comment by Scusemua** [comment]
The appendix of [this](https://arxiv.org/pdf/1910.05896.pdf) paper has a fairly detailed guide on deploying Wukong on AWS Lambda.

In that paper, we compared against Dask 0.18.0. 

More recently, we use the following versions of the Dask libraries:
```
dask                       1.2.2
dask-glm                   0.2.0
dask-ml                    1.0.0
dask-tensorflow            0.0.2
dask-xgboost               0.1.7
distributed                2.2.0
```

Also, there is some documentation here pertaining to setting up Wukong: 
- https://github.com/mason-leap-lab/Wukong/tree/socc2020/docs/setup
- https://github.com/mason-leap-lab/Wukong/blob/socc2020/AWS%20Lambda%20Task%20Executor/SAMREADME.md
- https://github.com/mason-leap-lab/Wukong/tree/socc2020/Static%20Scheduler/install

We will be updating the documentation as well as providing some installation utilities in the near future.

**Comment by Scusemua** [comment]
Closing for now.
